#!/bin/sh --

PREREQ=""
prereqs()
{
   echo "$PREREQ"
}

case $1 in
prereqs)
   prereqs
   exit 0
   ;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ ! -x /usr/bin/ykchalresp ]
then
    error_exit "Missing executable: /usr/bin/ykchalresp"
fi

copy_exec /usr/bin/ykchalresp

ldd /usr/bin/ykchalresp | awk '/=> \/.*/ { print $3 }' | while read lib; do
    copy_exec "$lib"
done

if [ ! -x /usr/bin/fdeyk_read_keyfile ]
then
    error_exit "Missing executable: /usr/bin/fdeyk_read_keyfile"
fi

copy_exec /usr/bin/fdeyk_read_keyfile
